# Generated by Django 3.2.4 on 2022-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20220705_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='posting_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30, unique=True)),
                ('docs', models.TextField()),
            ],
        ),
    ]
